# Generated by Django 4.0.10 on 2023-05-31 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetBinanceCOINM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name Asset')),
            ],
        ),
        migrations.CreateModel(
            name='AssetBinanceUSDT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name Asset')),
            ],
        ),
        migrations.CreateModel(
            name='PairBinanceCOINM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Name Pair')),
            ],
        ),
        migrations.CreateModel(
            name='PositionSideBinanceCOINM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name Position Side')),
            ],
        ),
        migrations.CreateModel(
            name='PositionSideBinanceUSDT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name Position Side')),
            ],
        ),
        migrations.CreateModel(
            name='SideBinanceCOINM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name Side')),
            ],
        ),
        migrations.CreateModel(
            name='SideBinanceUSDT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name Side')),
            ],
        ),
        migrations.CreateModel(
            name='SymbolBinanceCOINM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name Symbol')),
            ],
        ),
        migrations.CreateModel(
            name='SymbolBinanceUSDT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name Symbol')),
            ],
        ),
        migrations.CreateModel(
            name='TradeBinanceUSDT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_close', models.BooleanField(verbose_name='Closed trade')),
                ('open_datetime', models.DateTimeField(verbose_name='Open datetime')),
                ('close_datetime', models.DateTimeField(null=True, verbose_name='Close datetime')),
                ('open_price', models.FloatField(verbose_name='Open price')),
                ('close_price', models.FloatField(null=True, verbose_name='Close price')),
                ('realized_pnl', models.FloatField(default=0, verbose_name='Realized Pnl')),
                ('qty', models.FloatField(verbose_name='Qty')),
                ('position_side', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trades_info.positionsidebinanceusdt')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trades_info.symbolbinanceusdt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TradeBinanceCOINM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_close', models.BooleanField(verbose_name='Closed trade')),
                ('open_datetime', models.DateTimeField(verbose_name='Open datetime')),
                ('close_datetime', models.DateTimeField(null=True, verbose_name='Close datetime')),
                ('open_price', models.FloatField(verbose_name='Open price')),
                ('close_price', models.FloatField(null=True, verbose_name='Close price')),
                ('realized_pnl', models.FloatField(default=0, verbose_name='Realized Pnl')),
                ('qty', models.FloatField(verbose_name='Qty')),
                ('position_side', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trades_info.positionsidebinancecoinm')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trades_info.symbolbinancecoinm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderBinanceUSDT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binance_id', models.PositiveBigIntegerField(verbose_name='Binance ID')),
                ('order_id', models.PositiveBigIntegerField(verbose_name='Order ID')),
                ('price', models.FloatField(verbose_name='Price')),
                ('qty', models.FloatField(verbose_name='qty')),
                ('realized_pnl', models.FloatField(verbose_name='Realized Pnl')),
                ('quote_qty', models.FloatField(verbose_name='Quote Qty')),
                ('commission', models.FloatField(verbose_name='Commission')),
                ('datetime', models.DateTimeField()),
                ('maker', models.BooleanField()),
                ('buyer', models.BooleanField()),
                ('commission_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_commission', to='trades_info.assetbinanceusdt')),
                ('margin_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_margin', to='trades_info.assetbinanceusdt')),
                ('position_side', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trades_info.positionsidebinanceusdt')),
                ('side', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trades_info.sidebinanceusdt')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trades_info.symbolbinanceusdt')),
                ('trade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='trades_info.tradebinanceusdt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderBinanceCOINM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binance_id', models.PositiveBigIntegerField(verbose_name='Binance ID')),
                ('order_id', models.PositiveBigIntegerField(verbose_name='Order ID')),
                ('price', models.FloatField(verbose_name='Price')),
                ('qty', models.FloatField(verbose_name='qty')),
                ('realized_pnl', models.FloatField(verbose_name='Realized Pnl')),
                ('base_qty', models.FloatField(verbose_name='Base qty')),
                ('commission', models.FloatField(verbose_name='Commission')),
                ('datetime', models.DateTimeField()),
                ('maker', models.BooleanField()),
                ('buyer', models.BooleanField()),
                ('commission_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_commission', to='trades_info.assetbinancecoinm')),
                ('margin_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_margin', to='trades_info.assetbinancecoinm')),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trades_info.pairbinancecoinm')),
                ('position_side', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trades_info.positionsidebinancecoinm')),
                ('side', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trades_info.sidebinancecoinm')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trades_info.symbolbinancecoinm')),
                ('trade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='trades_info.tradebinancecoinm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
